export const CLASSES_DATA = [
  {
    id: 1,
    time: '06:00',
    duration: '60 phút',
    type: 'Yoga',
    typeColor: 'blue',
    room: 'Studio 1',
    name: 'Hatha Yoga Chào Ngày Mới',
    trainer: 'Li Wei-Hsuan',
    booked: 12,
    capacity: 20,
    day: 'Thứ 2'
  },
  {
    id: 2,
    time: '18:30',
    duration: '45 phút',
    type: 'HIIT',
    typeColor: 'red',
    room: 'Studio 2',
    name: 'Body Combat Đốt Mỡ',
    trainer: 'Marcus Adebayo',
    booked: 20,
    capacity: 20,
    day: 'Thứ 2'
  },
  {
    id: 3,
    time: '19:30',
    duration: '60 phút',
    type: 'Zumba',
    typeColor: 'purple',
    room: 'Studio 1',
    name: 'Zumba Dance Party',
    trainer: 'Sarah Jenkins',
    booked: 5,
    capacity: 30,
    day: 'Thứ 2'
  },
  {
    id: 4,
    time: '07:00',
    duration: '45 phút',
    type: 'Cycling',
    typeColor: 'yellow',
    room: 'Spinning Room',
    name: 'Đạp Xe Tốc Độ',
    trainer: 'Mateo Silva',
    booked: 15,
    capacity: 15,
    day: 'Thứ 3'
  },
  {
    id: 5,
    time: '18:00',
    duration: '60 phút',
    type: 'Body Pump',
    typeColor: 'orange',
    room: 'Studio 2',
    name: 'Sức Mạnh Toàn Diện',
    trainer: 'Trần Quốc Cường',
    booked: 18,
    capacity: 25,
    day: 'Thứ 3'
  },
  {
    id: 6,
    time: '06:30',
    duration: '60 phút',
    type: 'Pilates',
    typeColor: 'emerald',
    room: 'Studio 1',
    name: 'Pilates Căn Bản',
    trainer: 'Yuki Tanaka',
    booked: 10,
    capacity: 15,
    day: 'Thứ 4'
  },
  {
    id: 7,
    time: '19:00',
    duration: '60 phút',
    type: 'Yoga',
    typeColor: 'blue',
    room: 'Studio 1',
    name: 'Vinyasa Flow',
    trainer: 'Li Wei-Hsuan',
    booked: 25,
    capacity: 30,
    day: 'Thứ 5'
  },
  {
    id: 8,
    time: '18:30',
    duration: '45 phút',
    type: 'HIIT',
    typeColor: 'red',
    room: 'Studio 2',
    name: 'Cardio Đốt Mỡ',
    trainer: 'Aisha Bello',
    booked: 12,
    capacity: 20,
    day: 'Thứ 6'
  },
  {
    id: 9,
    time: '08:00',
    duration: '60 phút',
    type: 'Zumba',
    typeColor: 'purple',
    room: 'Studio 1',
    name: 'Zumba Cuối Tuần',
    trainer: 'Sarah Jenkins',
    booked: 28,
    capacity: 30,
    day: 'Thứ 7'
  },
  {
    id: 10,
    time: '09:30',
    duration: '60 phút',
    type: 'Yoga',
    typeColor: 'blue',
    room: 'Studio 1',
    name: 'Yoga Phục Hồi',
    trainer: 'Yuki Tanaka',
    booked: 15,
    capacity: 25,
    day: 'Chủ Nhật'
  },
  {
    id: 11,
    time: '17:00',
    duration: '60 phút',
    type: 'Body Pump',
    typeColor: 'orange',
    room: 'Studio 2',
    name: 'Tăng Cơ Chuyên Sâu',
    trainer: 'Kim Min-ho',
    booked: 14,
    capacity: 20,
    day: 'Thứ 4'
  },
  {
    id: 12,
    time: '08:00',
    duration: '45 phút',
    type: 'HIIT',
    typeColor: 'red',
    room: 'Studio 2',
    name: 'Functional Training',
    trainer: 'Mateo Silva',
    booked: 8,
    capacity: 20,
    day: 'Thứ 5'
  },
  {
    id: 13,
    time: '16:00',
    duration: '60 phút',
    type: 'Pilates',
    typeColor: 'emerald',
    room: 'Studio 1',
    name: 'Giảm Mỡ Cho Nữ',
    trainer: 'Nguyễn Thị Mai',
    booked: 10,
    capacity: 15,
    day: 'Thứ 6'
  },
  {
    id: 14,
    time: '10:00',
    duration: '60 phút',
    type: 'Body Pump',
    typeColor: 'orange',
    room: 'Studio 2',
    name: 'Kỹ Thuật Nâng Cao',
    trainer: 'Alexander Schmidt',
    booked: 12,
    capacity: 20,
    day: 'Thứ 7'
  }
];
